SEED:
  DETERMINISTIC: False
  SEED: 42

EXPERIMENT:
  NAME: PVT
  PROJECT: vanilla
  TAG: PVT,CIFAR-100,Vanilla

DATASET:
  IMG_SIZE: 224
  TYPE:
    TRAIN: cifar100
    TEST: cifar100-c
  BATCH_SIZE:
    TRAIN: 128
    TEST: 128
  NUM_WORKERS: 16
  AUGMENTATION:
    TT_BENCHMARK: True

MODEL:
  TYPE: pvt
  TRANSFORMER:
    PATCH_SIZE: [4, 2, 2, 2]
    HIDDEN_DIM: [64, 128, 320, 512]
    DEPTH: [2, 2, 2, 2]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIO: [8, 8, 4, 4]
    LN_EPS: 1e-6
    DROP_RATE: 0.0
    DROP_PATH_RATE: 0.1
    ATTENTION_DROP_RATE: 0.0
  PVT:
    SR_RATIO: [8, 4, 2, 1]

SOLVER:
  TYPE: AdamW
  TRAINER: base
  EPOCHS: 300
  LR_TYPE: warmup_cosine
  BASE_LR: 5.0e-4

ADAMW:
  BETAS: [0.9, 0.999]
  WEIGHT_DECAY: 0.05
WARMUP_COSINE:
  START_LR:  5.0e-7
  MIN_LR: 5.0e-6
  WARMUP_EPOCHS: 20