SEED:
  DETERMINISTIC: False
  SEED: 42

EXPERIMENT:
  NAME: ResNet-18
  PROJECT: vanilla_genformer
  TAG: ResNet-18,CIFAR-10,Vanilla,GenFormer

DATASET:
  IMG_SIZE: 224
  TYPE:
    TRAIN: cifar10
    TEST: cifar10-c
  SYNTHETIC_DATA: True
  BATCH_SIZE:
    TRAIN: 128
    TEST: 128
  NUM_WORKERS: 16
  AUGMENTATION:
    TT_BENCHMARK: True

SYNTHETIC_DATA:
  DIR_NAME: cifar10plus
  PERCENT: 1.0

MODEL:
  TYPE: ResNetv2TT
  CNN:
    DEPTH: 18
  RESNET:
    TRANS_FUN: basic_transform

SOLVER:
  TYPE: SGD
  TRAINER: base
  EPOCHS: 300
  LR_TYPE: cosine
  BASE_LR: 0.1

SGD:
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 5e-4

COSINE:
  MIN_LR: 0.0